spring:
  application:
    name: AICodeSmell

  datasource:
    username: root
    password: Sheep233
    url: jdbc:mysql://localhost:3306/ai_code_smell
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-test-query: select 1;
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl